[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
<<<<<<< HEAD
swiv_privacy = "5e4e9pooJgus8NcgdwZitZx1kF2vWZEA7MCTGi7BuKag"
=======
swiv_privacy = "8aAVXhM9uNdoijr7YJf3KG8yikHYdAUQZ6kmts9BBVLh"
>>>>>>> a8abaae5c40ec5e383b1f55dc88e7fef73a1fca2

[registry]
url = "https://api.apr.dev"

[provider]
<<<<<<< HEAD
cluster = "https://devnet.helius-rpc.com/?api-key=06c61703-7238-4f81-8ad0-c57dee8e2fc0"
=======
cluster = "https://devnet.helius-rpc.com/?api-key=6dbe7d1c-6aa3-48f4-94ab-c79ad7c1e0f2"
>>>>>>> a8abaae5c40ec5e383b1f55dc88e7fef73a1fca2
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
